name: AWS Nuke Scheduled

on:
  schedule:
    - cron: '0 22 * * *' # Midnight Paris time (UTC+2/UTC+1)
  workflow_dispatch:
  repository_dispatch:
    types: [AWS-Nuke-Scheduled]


jobs:
  trigger-nuke:
    uses: Synchroneyes/aws-sandbox-nuke/.github/workflows/nuke.yaml@main
    with:
      no-dry-run: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCOUNT_IDS: ${{ secrets.AWS_ACCOUNT_IDS }}
      SECRET_GITHUB: ${{ secrets.SECRET_GITHUB }}
